

//    Poser action playback
//      This program was generated by Project Biped Poser to playback a specific action.
//    Use it as the starting point for your projects!
//
//    Copyright (C) 2012  Jonathan Dowdall, Project Biped (www.projectbiped.com)
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#include <AcceleroMMA7361.h>

AcceleroMMA7361 accelero;

#include <Servo.h> 

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Constants
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
const int echoPin  = 7; //g
const int trigPin =  8;  //g
const int maximumServoShieldPosition = 2200;   // the maximum pulse duration for the servo shield (2ms pulse)
const int minimumServoShieldPosition = 800;   // the minimum pulse duration for the servo shield (1ms pulse)
const int numberOfServos             = 12;      // the number of servos
const int numberOfJoints             = 12;
String currentActionName = "";                //idicates the current action
int cont;
boolean playbackPlaying;

#define FRAME_LEN 33         // 30hz  -  frequencia do joystick

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Action Frames
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Joints positions are in degrees * 100 (home position is 0 degrees)
/////////////////////////////////////////////
//JOINT INDEXES
//
//RIGHT LEG JOINTS
// 0 Right Ankle (roll)
// 1 Right Lower Leg 
// 2 Right Knee 
// 3 Right Middle Leg 
// 4 Right Upper Leg 
// 5 Right Hip (roll)
//LEFT LEG JOINTS
// 6 Left Ankle (roll)
// 7 Left Lower Leg 
// 8 Left Knee 
// 9 Left Middle Leg 
// 10 Left Upper Leg 
// 11 Left Hip (roll)
/////////////////////////////////////////////
int servoPins[numberOfServos] = {22, 24, 26, 28, 30, 32, 38, 40, 42, 44, 46, 48};  // the pin for each servo 

int tras[38][numberOfJoints] = {
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },
                      { -187,  1200,  1200, -1200, -1200,     0,    20,  1200,  1200, -1200, -1200,     0 },
                      { -374,  2400,  2400, -2400, -2400,     0,    40,  2400,  2400, -2400, -2400,     0 },
                      { -561,  3600,  3600, -3600, -3600,     0,    60,  3600,  3600, -3600, -3600,     0 },
                      { -748,  4800,  4800, -4800, -4800,     0,    80,  4800,  4800, -4800, -4800,     0 },
                      { -935,  6000,  6000, -6000, -6000,     0,   100,  6000,  6000, -6000, -6000,     0 },
                      { -729,  4412,  6000, -6000, -6000,     0,    80,  4380,  6000, -6000, -6000,     0 },
                      { -522,  2825,  6000, -6000, -6000,     0,    60,  2760,  6000, -6000, -6000,     0 },
                      { -316,  1238,  6000, -6000, -6000,     0,    40,  1139,  6000, -6000, -6000,     0 },
                      { -109,  -348,  6000, -6000, -6000,     0,    19,  -479,  6000, -6000, -6000,     0 },
                      {   96, -1935,  6000, -6000, -6000,     0,     0, -2100,  6000, -6000, -6000,     0 },
                      {   96, -1935,  6000, -6000, -6000,     0,     0, -1080,  3600, -6000, -6000,     0 },
                      {   96, -1935,  6000, -6000, -6000,     0,     0,   -59,  1200, -6000, -6000,     0 },
                      {   96, -1935,  6000, -6000, -6000,     0,     0,   959, -1200, -6000, -6000,     0 },
                      {   96, -1935,  6000, -6000, -6000,     0,     0,  1980, -3600, -6000, -6000,     0 },
                      {   96, -1935,  6000, -6000, -6000,     0,     0,  3000, -6000, -6000, -6000,     0 },
                      {   96, -1146,  3633, -6000, -6000,     0,     0,  2014, -6000, -4126, -6000,     0 },
                      {   96,  -358,  1267, -6000, -6000,     0,     0,  1028, -6000, -2253, -6000,     0 },
                      {   96,   430, -1098, -6000, -6000,     0,     0,    42, -6000,  -380, -6000,     0 },
                      {   96,  1219, -3464, -6000, -6000,     0,     0,  -943, -6000,  1492, -6000,     0 },
                      {   96,  2008, -5830, -6000, -6000,     0,     0, -1929, -6000,  3365, -6000,     0 },
                      {   96,  2064, -6000, -6000, -6000,     0,     0, -2000, -6000,  1695, -3720,     0 },
                      {   96,  2064, -6000, -6000, -6000,     0,     0, -2000, -6000,  -204, -1320,     0 },
                      {   96,  2064, -6000, -6000, -6000,     0,     0, -2000, -6000, -2104,  1079,     0 },
                      {   96,  2064, -6000, -6000, -6000,     0,     0, -2000, -6000, -4004,  3479,     0 },
                      {   96,  2064, -6000, -6000, -6000,     0,     0, -2000, -6000, -5904,  5879,     0 },
                      {   96,  1301, -6000, -6000, -6000,  1126,     0, -2000, -6000, -6000,  5257,   -12 },
                      {   96,   498, -6000, -6000, -6000,  2311,     0, -2000, -6000, -6000,  4474,   -24 },
                      {   96,  -304, -6000, -6000, -6000,  3497,     0, -2000, -6000, -6000,  3692,   -37 },
                      {   96, -1107, -6000, -6000, -6000,  4683,     0, -2000, -6000, -6000,  2910,   -50 },
                      {   96, -1911, -6000, -6000, -6000,  5868,     0, -2000, -6000, -6000,  2128,   -63 },
                      {   96,   984, -1522, -6000, -6000,  6000,     0,   984, -1522, -6000,  -958,  2198 },
                      {   96,  4301,  3451, -6000, -6000,  6000,     0,  4301,  3451, -6000, -4292,  4712 },
                      {   87,  5400,  5400, -5400, -5400,  5400,     0,  5400,  5400, -5400, -5400,  5400 },
                      {   67,  4200,  4200, -4200, -4200,  4200,     0,  4200,  4200, -4200, -4200,  4200 },
                      {   48,  3000,  3000, -3000, -3000,  3000,     0,  3000,  3000, -3000, -3000,  3000 },
                      {   29,  1800,  1800, -1800, -1800,  1800,     0,  1800,  1800, -1800, -1800,  1800 },
                      {    9,   600,   600,  -600,  -600,   600,     0,   600,   600,  -600,  -600,   600 }
};
int GetUp[42][numberOfJoints] = {

                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },

                      { -187,  1200,  1200, -1200, -1200,     0,    20,  1200,  1200, -1200, -1200,     0 },

                      { -374,  2400,  2400, -2400, -2400,     0,    40,  2400,  2400, -2400, -2400,     0 },

                      { -561,  3600,  3600, -3600, -3600,     0,    60,  3600,  3600, -3600, -3600,     0 },

                      { -748,  4800,  4800, -4800, -4800,     0,    80,  4800,  4800, -4800, -4800,     0 },

                      { -935,  6000,  6000, -6000, -6000,     0,   100,  6000,  6000, -6000, -6000,     0 },

                      { -729,  6000,  6000, -6000, -6000,  1200,    80,  6000,  6000, -6000, -6000,  1200 },

                      { -522,  6000,  6000, -6000, -6000,  2400,    60,  6000,  6000, -6000, -6000,  2400 },

                      { -316,  6000,  6000, -6000, -6000,  3600,    40,  6000,  6000, -6000, -6000,  3600 },

                      { -109,  6000,  6000, -6000, -6000,  4800,    19,  6000,  6000, -6000, -6000,  4800 },

                      {   96,  6000,  6000, -6000, -6000,  6000,     0,  6000,  6000, -6000, -6000,  6000 },

                      {   96,  3600,  6000, -6000, -6000,  6000,     0,  3600,  6000, -6000, -6000,  6000 },

                      {   96,  1200,  6000, -6000, -6000,  6000,     0,  1200,  6000, -6000, -6000,  6000 },

                      {   96, -1200,  6000, -6000, -6000,  6000,     0, -1200,  6000, -6000, -6000,  6000 },

                      {   96, -3600,  6000, -6000, -6000,  6000,     0, -3600,  6000, -6000, -6000,  6000 },

                      {   96, -6000,  6000, -6000, -6000,  6000,     0, -6000,  6000, -6000, -6000,  6000 },

                      {   96, -5703,  6000, -6000, -6000,  4800,     0, -5700,  6000, -6000, -6000,  4800 },

                      {   96, -5406,  6000, -6000, -6000,  3600,     0, -5400,  6000, -6000, -6000,  3600 },

                      {   96, -5109,  6000, -6000, -6000,  2400,     0, -5100,  6000, -6000, -6000,  2400 },

                      {   96, -4812,  6000, -6000, -6000,  1200,     0, -4800,  6000, -6000, -6000,  1200 },

                      {   96, -4516,  6000, -6000, -6000,     0,     0, -4500,  6000, -6000, -6000,     0 },

                      {   96, -3412,  6000, -6000, -3600,     0,     0, -3400,  6000, -6000, -3600,     0 },

                      {   96, -2309,  6000, -6000, -1200,     0,     0, -2300,  6000, -6000, -1200,     0 },

                      {   96, -1206,  6000, -6000,  1200,     0,     0, -1200,  6000, -6000,  1200,     0 },

                      {   96,  -103,  6000, -6000,  3600,     0,     0,  -100,  6000, -6000,  3600,     0 },

                      {   96,  1000,  6000, -6000,  6000,     0,     0,  1000,  6000, -6000,  6000,     0 },

                      {   96,  2000,  6000, -6000,  6000,     0,     0,  2000,  6000, -6000,  6000,     0 },

                      {   96,  3000,  6000, -6000,  6000,     0,     0,  3000,  6000, -6000,  6000,     0 },

                      {   96,  4000,  6000, -6000,  6000,     0,     0,  4000,  6000, -6000,  6000,     0 },

                      {   96,  5000,  6000, -6000,  6000,     0,     0,  5000,  6000, -6000,  6000,     0 },

                      {   96,  6000,  6000, -6000,  6000,     0,     0,  6000,  6000, -6000,  6000,     0 },

                      {   96,  6000,  6000, -6000,  4321,     0,     0,  6000,  6000, -6000,  4321,     0 },

                      {   96,  6000,  6000, -6000,  2642,     0,     0,  6000,  6000, -6000,  2642,     0 },

                      {   96,  6000,  6000, -6000,   963,     0,     0,  6000,  6000, -6000,   963,     0 },

                      {   96,  6000,  6000, -6000,  -715,     0,     0,  6000,  6000, -6000,  -715,     0 },

                      {   96,  6000,  6000, -6000, -2394,     0,     0,  6000,  6000, -6000, -2394,     0 },

                      {   96,  6000,  6000, -6000, -4073,     0,     0,  6000,  6000, -6000, -4073,     0 },

                      {   96,  6000,  6000, -6000, -5752,     0,     0,  6000,  6000, -6000, -5752,     0 },

                      {   76,  4739,  4739, -4739, -4739,     0,     0,  4739,  4739, -4739, -4739,     0 },

                      {   53,  3339,  3339, -3339, -3339,     0,     0,  3339,  3339, -3339, -3339,     0 },

                      {   31,  1938,  1938, -1938, -1938,     0,     0,  1938,  1938, -1938, -1938,     0 },

                      {    8,   538,   538,  -538,  -538,     0,     0,   538,   538,  -538,  -538,     0 }

};
int walk[39][numberOfJoints] = { //g frames[numberOfFrames][numberOfJoints]
                      {  707, -2393,     0,     0, -3100,  1800, -1800,     0,   800,     0,     0, -2300 },
                      { 1990, -2130,     0,     0, -3100,  2664, -2578,     0,   800,     0,     0, -2300 },
                      { 2497, -2234, -2771,  2867,  1248,  2847, -2604,     0,   800,     0,  -573, -1917 },
                      { 2812, -2367, -5772,  5915,  5980,  2894, -2500,     0,   784,     0, -1190, -1507 },
                      { 2618, -2109, -5499,  5068,  5789,  2839, -2500,     0,   634,     0, -1094, -1581 },
                      { 2425, -1852, -5226,  4222,  5598,  2785, -2500,     0,   484,     0,  -999, -1655 },
                      { 2232, -1594, -4953,  3376,  5407,  2730, -2500,     0,   334,     0,  -903, -1729 },
                      { 2039, -1336, -4680,  2529,  5216,  2676, -2500,     0,   184,     0,  -808, -1803 },
                      { 1845, -1078, -4407,  1683,  5025,  2621, -2500,     0,    34,     0,  -712, -1877 },
                      { 1652,  -821, -4134,   836,  4834,  2566, -2500,     0,  -116,     0,  -617, -1951 },
                      { 1459,  -563, -3861,    -9,  4642,  2512, -2500,     0,  -266,     0,  -521, -2026 },
                      { 1370, -1976, -2600,     0,  1551,  2064, -2574,     0,  1400,     0, -4043, -1589 },
                      { 1113,  -472, -2600,     0,  4383,  1381, -2074,     0,  1400,     0, -1100, -1396 },
                      {  462,  -482, -2620,     0,  4047,  1008, -1567,     0,  1416,     0, -1115, -1316 },
                      { -188,  -493, -2640,     0,  3711,   635, -1060,     0,  1431,     0, -1129, -1237 },
                      { -839,  -503, -2659,     0,  3375,   262,  -553,     0,  1446,     0, -1143, -1158 },
                      {-1118,  -402, -1955,     0,  2643,  -308,  -231,  -488,  1153,     0, -1545,  -544 },
                      {-1324,  -280, -1123,     0,  1845,  -909,    52, -1063,   805,     0, -2014,   163 },
                      {-1530,  -159,  -291,     0,  1047, -1510,   335, -1638,   457,     0, -2483,   871 },
                      {-1735,   -37,   539,     0,   249, -2112,   619, -2213,   108,     0, -2953,  1578 },
                      {-2306,     0,   800,     0,     0, -2300,  1541, -2222,     0,     0, -3100,  2362 },
                      {-2643,     0,   800,     0,  -337, -2075,  2371, -2175, -1630,  1686,  -542,  2828 },
                      {-2531,     0,   800,     0, -1011, -1625,  2731, -2345, -4891,  5059,  4573,  2884 },
                      {-2500,     0,   687,     0, -1128, -1555,  2686, -2199, -5595,  5365,  5856,  2859 },
                      {-2500,     0,   537,     0, -1032, -1629,  2493, -1942, -5322,  4518,  5665,  2804 },
                      {-2500,     0,   387,     0,  -937, -1703,  2299, -1684, -5049,  3672,  5474,  2749 },
                      {-2500,     0,   236,     0,  -841, -1777,  2106, -1426, -4776,  2825,  5283,  2695 },
                      {-2500,     0,    86,     0,  -746, -1851,  1913, -1169, -4503,  1979,  5092,  2640 },
                      {-2500,     0,   -63,     0,  -650, -1926,  1720,  -911, -4229,  1132,  4900,  2585 },
                      {-2500,     0,  -213,     0,  -554, -2000,  1526,  -653, -3956,   286,  4709,  2531 },
                      {-2555,     0,   635,     0, -2536, -1798,  1397, -1359, -3139,   -89,  2838,  2279 },
                      {-2246,     0,  1400,     0, -2011, -1458,  1215,  -937, -2600,     0,  3518,  1605 },
                      {-1745,     0,  1410,     0, -1110, -1344,   690,  -479, -2613,     0,  4164,  1138 },
                      {-1237,     0,  1426,     0, -1124, -1265,    39,  -489, -2633,     0,  3828,   765 },
                      { -730,     0,  1441,     0, -1138, -1186,  -611,  -500, -2652,     0,  3492,   392 },
                      { -330,  -287,  1275,     0, -1380,  -792, -1046,  -444, -2246,     0,  2922,   -98 },
                      {  -46,  -862,   927,     0, -1850,   -84, -1252,  -323, -1415,     0,  2124,  -699 },
                      {  236, -1437,   578,     0, -2319,   623, -1458,  -201,  -583,     0,  1326, -1300 },
                      {  520, -2012,   230,     0, -2788,  1331, -1663,   -80,   248,     0,   528, -1901 }
};

int rightTurn[24][numberOfJoints] = {
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },
                      { -330,  -148,  -330,  -180,   400,  -340,   340,     0,     0,     0,   200,   256 },
                      { -660,  -296,  -660,  -360,   800,  -680,   680,     0,     0,     0,   400,   512 },
                      { -991,  -444,  -991,  -540,  1200, -1019,  1019,     0,     0,     0,   600,   768 },
                      {-1321,  -593, -1321,  -720,  1600, -1360,  1360,     0,     0,     0,   800,  1024 },
                      {-1651,  -741, -1651,  -900,  2000, -1700,  1700,     0,     0,     0,  1000,  1280 },
                      {-2022,  -741, -1701,  -560,  1839, -1739,  1920,   -20,     0,   460,  1320,  1544 },
                      {-2393,  -741, -1751,  -219,  1680, -1780,  2140,   -40,     0,   920,  1639,  1808 },
                      {-2764,  -741, -1800,   119,  1520, -1820,  2360,   -60,     0,  1380,  1960,  2072 },
                      {-3134,  -741, -1850,   460,  1360, -1860,  2580,   -80,     0,  1840,  2280,  2336 },
                      {-3505,  -741, -1900,   800,  1200, -1900,  2800,  -100,     0,  2300,  2600,  2600 },
                      {-3377,  -573, -1880,   480,  1140, -2039,  2520,   580,   220,  1760,  3000,  2420 },
                      {-3249,  -404, -1860,   159,  1080, -2180,  2240,  1260,   440,  1220,  3400,  2240 },
                      {-3121,  -235, -1839,  -159,  1019, -2320,  1960,  1939,   660,   680,  3800,  2060 },
                      {-2993,   -67, -1820,  -480,   960, -2460,  1679,  2620,   880,   139,  4200,  1880 },
                      {-2865,   101, -1800,  -800,   900, -2600,  1400,  3300,  1100,  -400,  4600,  1700 },
                      {-2651,  -299, -1800,  -577,  1202, -2600,  1328,  3193,  1100,  -400,  4444,  1700 },
                      {-2437,  -700, -1800,  -354,  1505, -2600,  1257,  3086,  1100,  -400,  4288,  1700 },
                      {-2223, -1101, -1800,  -131,  1808, -2600,  1186,  2979,  1100,  -400,  4132,  1700 },
                      {-1953, -1344, -1710,    40,  1943, -2470,  1073,  2750,  1045,  -380,  3809,  1614 },
                      {-1542, -1061, -1350,    32,  1534, -1950,   847,  2171,   825,  -300,  3007,  1275 },
                      {-1130,  -778,  -990,    23,  1125, -1430,   621,  1592,   605,  -220,  2205,   935 },
                      { -719,  -495,  -629,    14,   716,  -909,   395,  1013,   385,  -140,  1403,   594 },
                      { -308,  -212,  -270,     6,   306,  -390,   169,   434,   165,   -60,   601,   255 }

};

int lookDown[30][numberOfJoints] = {
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },
                      {    0,     0,    70,  -417,     6,     0,     0,     0,     0,  -411,     6,     0 },
                      {    0,     0,   141,  -835,    13,     0,     0,     0,     0,  -822,    13,     0 },
                      {    0,     0,   212, -1253,    20,     0,     0,     0,     0, -1233,    20,     0 },
                      {    0,     0,   282, -1671,    26,     0,     0,     0,     0, -1644,    26,     0 },
                      {    0,     0,   353, -2089,    33,     0,     0,     0,     0, -2056,    33,     0 },
                      {    0,     0,   424, -2507,    40,     0,     0,     0,     0, -2467,    40,     0 },
                      {    0,     0,   494, -2925,    47,     0,     0,     0,     0, -2878,    47,     0 },
                      {    0,     0,   565, -3343,    53,     0,     0,     0,     0, -3289,    53,     0 },
                      {    0,     0,   636, -3761,    60,     0,     0,     0,     0, -3701,    60,     0 },
                      {    0,     0,   706, -4179,    67,     0,     0,     0,     0, -4112,    67,     0 },
                      {    0,   306,  1091, -4179,    67,     0,     0,   303,   458, -4112,    67,     0 },
                      {    0,   613,  1475, -4179,    67,     0,     0,   606,   917, -4112,    67,     0 },
                      {    0,   920,  1859, -4179,    67,     0,     0,   910,  1376, -4112,    67,     0 },
                      {    0,  1226,  2243, -4179,    67,     0,     0,  1213,  1835, -4112,    67,     0 },
                      {    0,  1533,  2628, -4179,    67,     0,     0,  1516,  2293, -4112,    67,     0 },
                      {    0,  1840,  3012, -4179,    67,     0,     0,  1820,  2752, -4112,    67,     0 },
                      {    0,  2147,  3396, -4179,    67,     0,     0,  2123,  3211, -4112,    67,     0 },
                      {    0,  2453,  3780, -4179,    67,     0,     0,  2426,  3670, -4112,    67,     0 },
                      {    0,  2760,  4165, -4179,    67,     0,     0,  2730,  4128, -4112,    67,     0 },
                      {    0,  3067,  4549, -4179,    67,     0,     0,  3033,  4587, -4112,    67,     0 },
                      {    0,  2760,  4094, -3761,    60,     0,     0,  2730,  4128, -3701,    60,     0 },
                      {    0,  2453,  3639, -3343,    53,     0,     0,  2426,  3670, -3289,    53,     0 },
                      {    0,  2147,  3184, -2925,    47,     0,     0,  2123,  3211, -2878,    47,     0 },
                      {    0,  1840,  2729, -2507,    40,     0,     0,  1820,  2752, -2467,    40,     0 },
                      {    0,  1533,  2274, -2089,    33,     0,     0,  1516,  2293, -2056,    33,     0 },
                      {    0,  1226,  1819, -1671,    26,     0,     0,  1213,  1835, -1644,    26,     0 },
                      {    0,   920,  1364, -1253,    20,     0,     0,   910,  1376, -1233,    20,     0 },
                      {    0,   613,   909,  -835,    13,     0,     0,   606,   917,  -822,    13,     0 },
                      {    0,   306,   454,  -417,     6,     0,     0,   303,   458,  -411,     6,     0 }
};


int stand[5][numberOfJoints] = {
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 },
                      {    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,     0 }
};

int servoCalibrations[numberOfJoints][3] = {
                      {7678, -23, -7003}, 
                      {2284, 234, -337}, 
                      {1900, -100, 300}, 
                      {1900, -100, 200}, 
                      {2000, -400, -1135}, 
                      {800, -600, -3100}, 
                      {7600, 700, -6000}, 
                      {2900, 1000, 500}, 
                      {1900, 200, 0}, 
                      {2200, 100, 300}, 
                      {2600, 600, 300}, 
                      {1700, -300, -2700}
};


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class Action
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //  The Action class collects information necessary to perform a sequence of movements.     
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
  
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //Members
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  public:
    int             duration;      // Total duration of the action in milliseconds
    float           playbackTime;  // The playback time in milliseconds.
    unsigned long   lastTime;      // The playback time in milliseconds.
    int*            frames;        // Pointer to a two dimensional array containing the individual frames
    float           playbackSpeed; // The speed at which the action is played back (1 is realtime, 0.5 is half speed, 2.0 is twice realtime)
    boolean         playbackEnd;
    int frameCont;
    int testCont;
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //Methods
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  Action(int newDuration, void* newFrames)
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  {
    frames            = (int*)newFrames;
    duration          = newDuration;
    playbackTime      = 0;
    playbackSpeed     = 0.57;
    lastTime          = 0;
    currentActionName = "stand";
  }  
    
  //g
  void setWalkAction(){
    frames            = (int*)walk;
    duration          = (39 * 20);
    playbackTime      = 0;
    playbackSpeed     = 0.57;
    //lastTime          = 0;
    currentActionName = "walk";
  }
  
  void setStandAction(){
    frames            = (int*)stand;
    duration          = (5 * 20);
    playbackTime      = 0;
    playbackSpeed     = 0.57;
    //lastTime          = 0;
    currentActionName = "stand";
  }
  
  void setRightTurnAction(){
    frames            = (int*)rightTurn;
    duration          = (24 * 20);
    playbackTime      = 0;
    playbackSpeed     = 0.22;
    //lastTime          = 0;
    currentActionName = "rightTurn";
  }
  
  void setLookDownAction(){
    frames            = (int*)lookDown;
    duration          = (30 * 20);
    playbackTime      = 0;
    playbackSpeed     = 0.57;
    //lastTime          = 0;
    currentActionName =  "lookDown";
  }
  
  void setGetUpBehindAction(){
   
   frames            = (int*)tras;
   duration          = (38 * 20);
   playbackTime      = 0;
   playbackSpeed     = 0.20;
    currentActionName= "GetUpTras";
   
    
  }
  
  void setGetUpFrenteAction(){
    
    frames            = (int*)GetUp;
    duration          = (42 * 20);
   playbackTime      = 0;
   playbackSpeed     = 0.20;
   currentActionName= "GetUpFrente";
   //lastTime          = 0;
  }
  //g#
  
  ///////////////////////////////////////g
  void setPlaybackSpeed(float newSpeed){//g
  ////////////////////////////////////////g
    playbackSpeed = newSpeed;
  }
  ///////////////////////////////////////g
  
  boolean playbackEndCheck(){
    return playbackEnd;
  }
  
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  void Update()
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  {  
     // Get the current time.
     unsigned long currentTime = millis(); 
   
     // Update the playback time.
     playbackTime += (playbackSpeed * (float)(currentTime - lastTime));
     
     // Loop if the playback time is past the end of the action.
     playbackEnd = false;
     if(playbackTime > duration){
       playbackTime = playbackTime - duration;
       playbackEnd = true; 
       //g#  
     }  
     
     // Remember the time.
     lastTime = currentTime; 
  }

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  void GetCurrentFrame(int* frame)
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  {
      //update each servo
      int* sourceFrame = frames + ((int)playbackTime/20)*numberOfJoints;      
      for (int joint = 0; joint < numberOfJoints; joint++)
          frame[joint] = sourceFrame[joint]; 
  }

};


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Actions
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Action myAction(numberOfFrames * 20 , frames); //the action
//Action walkAction(39 * 20 , walk); 
Action standAction(5 * 20 , stand); 
//Action rightTurnAction(24 * 20 , rightTurn);
//Action lookDownAction(30 * 20 , lookDown);
Action* currentAction; 

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Variables
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Servo servos[numberOfServos];  // create servo object to control a servo 

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void setup()
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
 //start up the communication
  Serial.begin(38400);  
  
  accelero.begin(13, 12, 11, 10, A0, A1, A2);
  accelero.setARefVoltage(3.3);                   //sets the AREF voltage to 3.3V
  accelero.setSensitivity(HIGH);                   //sets the sensitivity to +/-6G

  //set the initial action
  //currentAction = &myAction; 
  currentAction = &standAction;//g
  playbackPlaying = true;
  //wait for a second to begin (keeps the communication line open in case a new program is being downloaded)
  delay(1000);    
  

  
  
  //initialize the servos
  initializeServos();
  
  //g
  // Apply the servo calibrations to the joint positions.
  initializeActions();//g
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void loop()
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
  //this is the main update loop for the microcontroller

  if(Serial.available() > 0) UpdateActionJoystick();
  else UpdateActionAccelero();
   
  //get the frame from the current action
  int frame[numberOfServos];
  if(playbackPlaying)
    currentAction->GetCurrentFrame(frame);
   
  //set the servo positions for this frame number
  SetServoPositions(frame);
  // Add a little delay.
  delay(1); 
     
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void UpdateActionJoystick()
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
   // TODO (you) : add some logic for your action here!
   //check to see if the robot is standing
  char j;
  j = Serial.read();
  Serial.println(j);
    
  if(currentAction->playbackEndCheck()){ //avoid changes in the middle of an animation     
       ///////////// STAND   
        if(currentActionName == "stand"){
          Serial.println(" STAND Joystick");
          
          if (j == 'F') { currentAction->setWalkAction(); 
                               Serial.println(" stand => setWalk ");  }
          else if (j == 'D') { currentAction->setRightTurnAction();
                               Serial.println(" stand => setRight ");  }
          else if (j == 'P') { currentAction->Update();
                               Serial.println(" update stand ");  }         
        } 
        /////////////// WALK
        else if(currentActionName == "walk"){  
          Serial.println(" WALK Joystick"); 
  
          if (j == 'D') { currentAction->setRightTurnAction();
                               Serial.println(" walk => setRight ");  }
          else if (j == 'P') { currentAction->setStandAction(); 
                               Serial.println(" walk => setStand ");  }
          else if (j == 'F') { currentAction->Update();
                               Serial.println(" update walk ");  }
       }   
       ////////////// RIGHT
       else if(currentActionName == "rightTurn"){
          Serial.println(" RIGHT Joystick");  
  
          if (j == 'F') { currentAction->setWalkAction(); 
                               Serial.println(" right => setWalk ");  }
          else if (j == 'P') { currentAction->setStandAction(); 
                               Serial.println(" right => setStand ");  }
          else if (j == 'D') { currentAction->Update(); 
                               Serial.println(" update right ");  }
       }   
    } else currentAction->Update();
    delay(FRAME_LEN);  
} 


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void UpdateActionAccelero()
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
  // TODO (you) : add some logic for your action here!
  //check to see if the robot is standing
  unsigned int distance = MeasureDistance();
  int z = posicao_z();
  int y = posicao_y();

  if(currentAction->playbackEndCheck()){ //avoid changes in the middle of an animation
    ///////////// STAND
    if ( currentActionName =="GetUpTras"){
      Serial.println(" GET UP BEHIND");
      if (y < -40)currentAction->Update();
      else currentAction->setGetUpFrenteAction();
    }
    else if ( currentActionName =="GetUpFrente"){
      Serial.println(" GET UP FRONT");
      Serial.println(z);
      Serial.println(y);
      if (z < 0) currentAction->Update();
      //else currentAction->setWalkAction();
      else currentAction->setStandAction();
    }
    else if(currentActionName == "stand"){
      Serial.println(" STAND Acelerometro");
      if (y < -40)currentAction->setGetUpBehindAction();
      else if (z < -0) currentAction->setGetUpFrenteAction();
      else if(distance>20)currentAction->setWalkAction();
      else currentAction->Update();
    }
    /////////////// WALK
    else if(currentActionName == "walk"){
      Serial.println(" WALK Acelerometro");
      if (y < -40)currentAction->setGetUpBehindAction();
      else if (z < -0) currentAction->setGetUpFrenteAction();
      else if(distance<10)currentAction->setStandAction();
      else if(distance>10&&distance<30)currentAction->setRightTurnAction();
      else currentAction->Update();
    }
    ////////////// RIGHT
    else if(currentActionName == "rightTurn"){
      Serial.println(" RIGHT Acelerometro");
      if (y < -40)currentAction->setGetUpBehindAction();
      else if (z < 0) currentAction->setGetUpFrenteAction();
      else if(distance>40)currentAction->setStandAction();
      else currentAction->Update();
    }
    // ////////////// LOOK
    // else if(currentActionName == "walk" && cont>=4){
    // currentAction->setLookDownAction();
    // if(cont>=5){
    // playbackPlaying = false;
    // if(cont>=100){
    // playbackPlaying = true;
    // cont=0;
    // currentAction->setStandAction();
    // }
    // else cont++;
    // }
    // else{
    // cont++;
    // currentAction->Update();
    // }
    // }
    // cont++;
  } else currentAction->Update();  
} 


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void initializeServos()
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{   
  // Assign the correct pin to each servo.
  for(int s = 0; s < numberOfServos; s++)
    servos[s].attach(servoPins[s]);  
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void SetServoPositions(int* frame)
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
  //update each servo
  for (int servo = 0; servo < numberOfServos; servo++)
  {   
      // each servo position is sent as a 2 byte value (high byte, low byte) integer (from -32,768 to 32,767)
      // this number is encoding the angle of the servo. The number is 100 * the servo angle.  This allows for the
      // storage of 2 significant digits(i.e. the value can be from -60.00 to 60.00 and every value in between).
      // Also remember that the servos have a range of 120 degrees. The angle is written in positions
      // which range from a minimum of 800 (-60 degrees) and go to a maximum of 2200 (60 degrees)
          
      int value = frame[servo];      
      
      // flip for the left leg.
      if(servo >= numberOfServos/2)
        value = map(value, -6000,6000,6000,-6000);
      
      servos[servo].write(map(value, -6000,6000,800,2200));              // tell servo to go to position in variable 'pos'       

  }
}


//g
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void initializeActions()//g
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{   
  //And ApplyCalibration
  // Apply the servo calibrations to each frame of the animation.
  // This is done before hand to keep from slowing down the playback.
  // The frames could also be stored with the calibrations already
  // applied, however leaving the calibration seperate allows other
  // ROFIs to use this same action with their own calibration.
  
  
  //walk
  int numberOfFrames=39;
  for(int f = 0; f < numberOfFrames; f++)
    for(int s = 0; s < numberOfServos; s++)    
      walk[f][s] = CorrectJointAngle(walk[f][s], s);
     
  //stand
  numberOfFrames=5;
  for(int f = 0; f < numberOfFrames; f++)
    for(int s = 0; s < numberOfServos; s++)    
      stand[f][s] = CorrectJointAngle(stand[f][s], s); 
      
  //rightTurn
  numberOfFrames=24;
  for(int f = 0; f < numberOfFrames; f++)
    for(int s = 0; s < numberOfServos; s++)    
      rightTurn[f][s] = CorrectJointAngle(rightTurn[f][s], s); 
      
  //lookDown
  numberOfFrames=30;
  for(int f = 0; f < numberOfFrames; f++)
    for(int s = 0; s < numberOfServos; s++)    
      lookDown[f][s] = CorrectJointAngle(lookDown[f][s], s);
      
  numberOfFrames=42;
  for(int f = 0; f < numberOfFrames; f++)
    for(int s = 0; s < numberOfServos; s++)    
       GetUp[f][s] = CorrectJointAngle(GetUp[f][s], s);
       
             
  numberOfFrames=38;
  for(int f = 0; f < numberOfFrames; f++)
    for(int s = 0; s < numberOfServos; s++)    
       tras[f][s] = CorrectJointAngle(tras[f][s], s);
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
double CorrectJointAngle(double inputAngle, int servo)
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
  // The input angle is what the angle should be.42
  // The corrected angle is the angle that has to be sent to the servo to achieve the input angle.
  if (inputAngle > 0)
    // Do a two point calibration between the middle and high corrected values.
    return map(inputAngle, 0, 4500, 0 + servoCalibrations[servo][1], 4500 + servoCalibrations[servo][2]);
  else
    // Do a two point calibration between the low and middle corrected values.
    return map(inputAngle, -4500, 0, -4500 + servoCalibrations[servo][0], 0 + servoCalibrations[servo][1]);
}
//#g

//g
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
long MeasureDistance()
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
  //g
  int maximumRange = 200; // Maximum range needed
  int minimumRange = 0; // Minimum range needed
  long duration, distance; // Duration used to calculate distance
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  
  /* The following trigPin/echoPin cycle is used to determine the
  distance of the nearest object by bouncing soundwaves off of it. */ 
  digitalWrite(trigPin, LOW); 
  delayMicroseconds(2); 
  
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10); 
   
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
   
  //Calculate the distance (in cm) based on the speed of sound.
  distance = duration/58.2; //g
   
  if (distance >= maximumRange || distance <= minimumRange){
  /* Send a negative number to computer to indicate "out of range" */
  
  }
  else return distance;//g
}

int posicao_z()
{

  int posicao_z = accelero.getZAccel();  
  

  return posicao_z;
}

int posicao_y()
{
  
  int posicao_y = accelero.getYAccel();
  
  return posicao_y;
 
  
}

//#g


