set(_CATKIN_CURRENT_PACKAGE "rofi_robot")
set(rofi_robot_VERSION "0.0.0")
set(rofi_robot_MAINTAINER "lsa <lsa@todo.todo>")
set(rofi_robot_PACKAGE_FORMAT "1")
set(rofi_robot_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(rofi_robot_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(rofi_robot_BUILDTOOL_DEPENDS "catkin")
set(rofi_robot_BUILDTOOL_EXPORT_DEPENDS )
set(rofi_robot_EXEC_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(rofi_robot_RUN_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(rofi_robot_TEST_DEPENDS )
set(rofi_robot_DOC_DEPENDS )
set(rofi_robot_URL_WEBSITE "")
set(rofi_robot_URL_BUGTRACKER "")
set(rofi_robot_URL_REPOSITORY "")
set(rofi_robot_DEPRECATED "")